version: "3"

services:

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql


  backend:
    image: hiringback:latest
    ports:
      - "8085:8085"
    depends_on:
      - mysqldb
    # restart: unless-stopped
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/testSec?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "29618730Ab#",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'


volumes:
  db: